spring.application.name=studymate

spring.datasource.url=jdbc:postgresql://localhost:5432/studymate
spring.datasource.username=postgres
spring.datasource.password=Gololed777@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
